eureka:
  client:
    service-url:
      defaultZone: http://fangxianyu-eureka:8080/eureka/
spring:
  datasource:
    url: jdbc:mysql://fangxianyu-mysql:3306/goods_service
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver



