eureka:
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/goods_service
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8804


